apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Graphite
    type: graphite
    access: proxy
    url: http://graphite:8080
    jsonData:
      graphiteVersion: '1.1'
  - name: VictoriaMetrics
    type: victoriametrics-metrics-datasource
    access: proxy
    url: http://victoria:8428
    jsonData:
      httpMethod: GET