global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:8080']
    relabel_configs:
      - replacement: production
        target_label: env
    metric_relabel_configs:
      - source_labels: [ app_instance ]
        regex: "(.*):(.*)"
        replacement: "${1}"
        target_label: app_hostname
        action: replace
