global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'driver-location-service'
    static_configs:
      - targets: ['driver-location-service:8080']
    relabel_configs:
      - target_label: instance
        replacement: 'node-01'

  - job_name: 'track-analyzer-service'
    static_configs:
      - targets: ['track-analyzer-service:8080']
    relabel_configs:
      - target_label: instance
        replacement: 'node-01'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - target_label: instance
        replacement: 'node-01'

  - job_name: 'loki'
    static_configs:
      - targets: [ 'loki:3100' ]
    relabel_configs:
      - target_label: instance
        replacement: 'node-01'

  - job_name: 'redis_exporter'
    static_configs:
      - targets: [ 'redis_exporter:9121' ]
    relabel_configs:
      - target_label: instance
        replacement: 'node-01'