global:
  scrape_interval: 10s
  scrape_timeout: 1s

scrape_configs:
  - job_name: ride-request
    static_configs:
      - targets: ['ride-request:8080']
  - job_name: matching-engine
    static_configs:
      - targets: ['matching-engine:8080']
  - job_name: driver-location
    static_configs:
      - targets: ['driver-location:8080']