services:
  app:
    container_name: app
    build:
      context: app
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:latest
    command:
      - "--log.level=debug"
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
