apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Graphite
    type: graphite
    access: proxy
    url: http://graphite:8080
    jsonData:
      graphiteVersion: '1.1'

  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "^.*?traceI[d|D]=(\\w+).*$"
          name: traceId
          url: '$${__value.raw}'

  - name: Pyroscope
    type: phlare
    access: proxy
    uid: pyroscope
    url: http://pyroscope:4040
    jsonData:
      backendType: pyroscope