apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app-deployment
  labels:
    app: my-go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-go-app
  template:
    metadata:
      labels:
        app: my-go-app
    spec:
      containers:
      - name: my-go-app
        image: my-go-app:latest
        imagePullPolicy: Never # Important!
        ports:
        - containerPort: 8080
          name: web
