services:
  app:
    container_name: app
    build:
      context: app
    ports:
      - "8080:8080"
      - "10000:10000"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
